### Hello Business
GET http://127.0.0.1:8081/business/hello
Content-Type: application/x-www-form-urlencoded

### Station
POST http://127.0.0.1:8000/business/admin/station/save
Content-Type: application/json

{
  "name": "武汉",
  "namePinyin": "WUHAN",
  "namePy": "WH"
}
### Generate Train Seat
GET http://127.0.0.1:8081/business/admin/train/gen-seat/K122
Content-Type: application/x-www-form-urlencoded
