###
# 测试首次的api
GET http://localhost:8000/member/1
Accept: application/json

# 测试访问网关
###
GET http://127.0.0.1:8000/member/1
Accept: application/json

###
GET http://127.0.0.1:8000/member/member/count
Accept: application/json

###

POST http://127.0.0.1:8000/member/member/register
Content-Type: application/x-www-form-urlencoded

mobile=
