###
# 测试首次的api
GET http://localhost:8080/member/1
Accept: application/json
#
###测试访问网关
GET http://localhost:8000/member/member/1
Accept: application/x-www-form-urlencoded

# 测试访问网关
###
POST http://127.0.0.1:8080/member/register
Accept: application/x-www-form-urlencoded
mobile=12212341234

###
GET http://127.0.0.1:8000/member/member/count
Accept: application/json

### register

POST http://127.0.0.1:8080/member/member/register
Content-Type: application/json

{
 "mobile":"13088880000"
# "code":"8888"
}

### 登录member
POST http://127.0.0.1:8000/member/member/login
Content-Type: application/json

{
 "mobile":"13088880000",
 "code":"8888"
}


> {%
    client.log(JSON.stringify(response.body));
    client.log(JSON.stringify(response.body.content.token));
    client.global.set("token", response.body.content.token);
%}

### sendcode
POST http://localhost:8000/member/member/send-code
Content-Type: application/json

{
  "mobile":"13088880000"
}

