### 测试插入成员信息
POST http://127.0.0.1:8080/member/passenger/save
Content-Type: application/json
token:{{token}}
#获取缓存的token

{
  "name":"passengerOne",
  "idCard":"3231123123123",
  "type":"1"
}

### 测试获取成员信息
GET http://127.0.0.1:8080/member/passenger/query-list
Content-Type: application/json
token:{{token}}
#获取缓存的token


### 登录member

POST http://127.0.0.1:8000/member/member/login
Content-Type: application/json

{
  "mobile":"13088880000",
  "code":"8888"
}
